CREATE or ALTER PROCEDURE spAddToWishList
(@UserId INT,@BookId INT)
As
BEGIN TRY
 INSERT INTO WishListTable (UserId, BookId)VALUES (@UserId,@BookId);
 END TRY 
 BEGIN CATCH
 SELECT ERROR_MESSAGE() AS ERROR
 END CATCH

