CREATE TABLE ORDERTABLE(
OrderId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
UserId INT FOREIGN KEY (UserId) REFERENCES UserDetails(UserId),
BookId INT FOREIGN KEY (BookId) REFERENCES BOOKS(bookId),
AddressId INT FOREIGN KEY (AddressId) REFERENCES ADDRESSTABLE(AddressId),
TotalPrice INT,
TotalQuantity INT,
OrderDate Date);

DROP TABLE ORDERTABLE

SELECT * FROM ORDERTABLE