CREATE TABLE WishListTable
(
	WishListId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	UserId INT FOREIGN KEY REFERENCES UserDetails(UserId),
	BookId INT FOREIGN KEY REFERENCES BOOKS(BookId)
);

SELECT * FROM UserDetails